# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a3332954238efd78cede1d6e86ffd6c21344b63f69b3482ae05886cc4452743a266ff98ab10ded3529451f3c2e0d23178bea1da594c12592ede5596d34c40b9

test:
  secret_key_base: a69c8b0ea4ee8860a64b1a741c61a0b3b2f6c8d1517c2a82917c133879ebd57ae178388a07d1a701f8853658fbc93284df7776495667f422ada1f9cf14af6104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
